### ISSUE TITLE
Drawing only possible on a fraction of the screen

### ISSUE THREAD

**Issue by c0dev0id** [JohnMcLear/ep_draw#30]
I really like the idea. Especially with webrtc in etherpad, this makes a whole new form of collaboration possible. 

In my installation ep_draw only allows to draw to the top fraction of the screen.
Test here: https://pad.new.uugrn.org/p/drawtest

![image](https://user-images.githubusercontent.com/44190565/82890551-aa32ac80-9f4c-11ea-997d-3b158b1f5764.png)

Draw itself works fine... see: https://draw.uugrn.org

**Comment by c0dev0id** [comment]
Oh, I see this has been fixed at https://github.com/JohnMcLear/ep_draw/issues/28 ... sorry for the noise. I'll update.

**Comment by c0dev0id** [comment]
No - it still does happen. I'm on commit 8ed9034f439b6da6d396d65e84028f7213e9177f, cleared the browser cache, restarted etherpad-lite... no change.

**Comment by JohnMcLear** [comment]
I'm gonna try look at this today.

**Comment by JohnMcLear** [comment]
Fixed.  Please update :)

**Comment by JohnMcLear** [comment]
Btw what happened here was Etherpad went 1.8.3 and I thought I patched it but my patch was on another server and it was a 2 line patch and I forgot to bring both lines of fixes over..  These were busy days and because ep_draw and etherdraw both need a rewrite I'm just quickly throwing stuff out to keep things moving.

**Comment by Sayao32** [comment]
Working great with lastest update :) Thanks a lot for your work !

**Comment by c0dev0id** [comment]
Yep, works! Thank you very much!
